language: go
#sudo: required
go:
  - 1.5.3
  - 1.6
  - tip

env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1

before_install:
  - go get -v github.com/Masterminds/glide

#install: true
script:
  - glide update
  - make validate
  - make test
  - make bin

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  allow_failures:
    - go: tip
